### ISSUE TITLE
no delegation sets

### ISSUE THREAD

**Issue by zocoloco** [plesk/ext-route53#12]
Using Plesk 12.5.30
Installed extension from https://ext.plesk.com/packages/ed1860ee-45c5-4e2b-b6b7-44e5da69dca5-route53
Accepts API key - but there are no delegation sets
Error: setFailed to load resource: The network connection was lost.

removed extension and tried to install again from the Extensions Catalog. Same results
removed extension and tried to install again from GitHub - corrupt XML.

**Comment by zocoloco** [comment]
any ideas on why this may be happening?

**Comment by xgin** [comment]
Hello @zocoloco 
I cannot reproduce the error on any of my VPS.
Does it occur when you submit a creation of new delegation set?
May be there are some network issues, e.g. with firewall?

**Comment by zocoloco** [comment]
When I click on the tab - Reusable Delegation Sets - I get a blank screen. If I look at the browser error, it shows an error: GET https://domain.com:8443/modules/route53/index.php/index/delegation-set net::ERR_INCOMPLETE_CHUNKED_ENCODING. I've tried in two browsers. I use these same browsers in other applications that access AWS - without an issue. Not sure why this doesn't work. Guess I'll just continue to do Route 53 manually.

**Comment by ayamshanov** [comment]
Unfortunately, we have to close an open issue because Plesk 12.5.30 has reached EOL and we couldn't reproduce the issue in Plesk Onyx and Obsidian versions with the latest version of the extension.
