### ISSUE TITLE
Subdomains don't work

### ISSUE THREAD

**Issue by ordin2342** [plesk/ext-route53#16]
Thanks for this great extension. 

But there's an issue with subdomains. Right now subdomains are created as new **Hosted Zone**, containing records like _MX, mail.subdomain.domain.com, ftp.subdomain.domain.com_ etc.

One issues is that this doesn't work, I cannot access subdomain.domain.com via webbrowser. 
The other issue is that I don't need all these records. 

I've read somewhere in AWS Docs that a subdomain should be created as simple A record part of it's existing (root) Hosted zone. When I manually create a subdomain on Route 53 as record of the Hosted Zone for domain.com, not as new hosted zone, I can access the subdomain without issues.

Could you please add an option to create a subdomain as record and not as new hosted zone?

Cheers,
Bob.

EDIT: Changed some text to be more clear about the issue.

**Comment by ayamshanov** [comment]
Hi ordin2342,

**Could you provide steps to reproduce the issue?
I have tried to reproduce your issue but without success.** 

My steps were:
1. Install Plesk, create a test domain "demo.plesk.com"
2. Install Route53, "Sync all zones"
3. Create a new A-record "my.test.domain" (+"demo.plesk.com") with IP-address "123.123.123.123"

How I checked:
1. I watched to created records in AWS Route53 Console. All looks good, the new long domain exists.
2. I queried information from one applied of AWS NS-servers:

```
# dig @ns-607.awsdns-11.net. my.test.domain.demo.plesk.com.

; <<>> DiG 9.9.4-RedHat-9.9.4-51.el7_4.2 <<>> @ns-607.awsdns-11.net. my.test.domain.demo.plesk.com.
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 18832
;; flags: qr aa rd; QUERY: 1, ANSWER: 1, AUTHORITY: 4, ADDITIONAL: 1
;; WARNING: recursion requested but not available

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;my.test.domain.demo.plesk.com. IN      A

;; ANSWER SECTION:
my.test.domain.demo.plesk.com. 300 IN   A       123.123.123.123

;; AUTHORITY SECTION:
demo.plesk.com.         172800  IN      NS      ns-1225.awsdns-25.org.
demo.plesk.com.         172800  IN      NS      ns-1701.awsdns-20.co.uk.
demo.plesk.com.         172800  IN      NS      ns-456.awsdns-57.com.
demo.plesk.com.         172800  IN      NS      ns-607.awsdns-11.net.

;; Query time: 92 msec
;; SERVER: 205.251.194.95#53(205.251.194.95)
;; WHEN: Tue Mar 06 20:06:32 NOVT 2018
;; MSG SIZE  rcvd: 211

#
```

**Comment by ayamshanov** [comment]
I have made the second test:

My step was:
1. I created a subdomain "my-new-subdomain" for the domain in webspace.

How I checked:
1. I watched that records in AWS Route53 Console was created. All looks good, the new subdomain exists in Route53.
2. I queried information from one applied of AWS NS-servers:
```
# dig @ns-607.awsdns-11.net. my-new-subdomain.demo.plesk.com.

; <<>> DiG 9.9.4-RedHat-9.9.4-51.el7_4.2 <<>> @ns-607.awsdns-11.net. my-new-subdomain.demo.plesk.com.
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 3397
;; flags: qr aa rd; QUERY: 1, ANSWER: 1, AUTHORITY: 4, ADDITIONAL: 1
;; WARNING: recursion requested but not available

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;my-new-subdomain.demo.plesk.com. IN    A

;; ANSWER SECTION:
my-new-subdomain.demo.plesk.com. 300 IN A       52.ip.161.213

;; AUTHORITY SECTION:
demo.plesk.com.         172800  IN      NS      ns-1225.awsdns-25.org.
demo.plesk.com.         172800  IN      NS      ns-1701.awsdns-20.co.uk.
demo.plesk.com.         172800  IN      NS      ns-456.awsdns-57.com.
demo.plesk.com.         172800  IN      NS      ns-607.awsdns-11.net.

;; Query time: 84 msec
;; SERVER: 205.251.194.95#53(205.251.194.95)
;; WHEN: Tue Mar 06 20:23:20 NOVT 2018
;; MSG SIZE  rcvd: 213

#
```

**Comment by ayamshanov** [comment]
Unfortunately, we have to close an open issue because we couldn't reproduce the issue.
