### ISSUE TITLE
Issue in creating Delegation Set

### ISSUE THREAD

**Issue by Deepesh316** [plesk/ext-route53#19]
Hello,

I have installed the Amazon Route 53 Extension(Downloaded from GitHub with Version 2.4) in Plesk ( Plesk Onyx Version 17.5.3). Configured the API Authorization Details. Also we have setup our white label name servers that needs to be used within the extension. Upon Creating New Delegation Set, encountered an error " Error: The specified delegation set contains associated hosted zones. ". The same error appears after removing the delegation set. We want to display our whitelabel name server instead of aws name server.  

![delegation-error](https://user-images.githubusercontent.com/21241802/30467691-24e9b4a6-9a04-11e7-9ed8-541a65f04a1e.png)

Please help us to find the issue  ASAP.

**Comment by ayamshanov** [comment]
Since version 2.8.0, the Route 53 extension supports white-labeling:
> It is now possible to have white-label or vanity name server with Amazon Route 53. To configure them, users need to select the "Manage NS and SOA records" checkbox and then follow step 7 and further in the [Amazon Route 53 guide](https://docs.aws.amazon.com/Route53/latest/DeveloperGuide/white-label-name-servers.html).
