### ISSUE TITLE
Way to force plesk zone to amazone zone?

### ISSUE THREAD

**Issue by nielsvr** [plesk/ext-route53#23]
I have a domain, which appears not to sync to Amazon. Things I tried;

- Remove the zone from Amazon, used the Mass Sync option. Zone is not recreated
- Recreated manually on Amazon, edited the zone in Plesk. Zone is not updated

Is there a way to force a specific zone or to find out why it not gets created/synced?

**Comment by ayamshanov** [comment]
Hi nielsvr,

Could you please enable debug, click the "Mass Sync" and check log-file?
- How to enable debug: https://support.plesk.com/hc/en-us/articles/213408889 , changes take effect immediately.
- Log-file: /usr/local/psa/admin/logs/panel.log


P.S. Don't forget to disable debug when it not required.

**Comment by nielsvr** [comment]
Done, interesting, this is the domain that does not get created (with subdomains)

> [2018-05-30 10:40:35.000] DEBUG [util_exec] [5b0e7fa2f422e] Starting: dnsmng --update yvey.nl --without-reverse
> [2018-05-30 10:40:35.302] DEBUG [util_exec] [5b0e7fa2f422e] Finished in 0.30201s, Error code: TRUE
> [2018-05-30 10:40:35.303] DEBUG [util_exec] [5b0e7fa34a0d0] Starting: dnsmng --update consult.yvey.nl --without-reverse
> [2018-05-30 10:40:35.612] DEBUG [util_exec] [5b0e7fa34a0d0] Finished in 0.30855s, Error code: TRUE
> [2018-05-30 10:40:35.614] DEBUG [util_exec] [5b0e7fa395e3f] Starting: dnsmng --update events.yvey.nl --without-reverse
> [2018-05-30 10:40:35.937] DEBUG [util_exec] [5b0e7fa395e3f] Finished in 0.32248s, Error code: TRUE
> [2018-05-30 10:40:35.938] DEBUG [util_exec] [5b0e7fa3e4ecf] Starting: dnsmng --update world.yvey.nl --without-reverse
> [2018-05-30 10:40:36.214] DEBUG [util_exec] [5b0e7fa3e4ecf] Finished in 0.27628s, Error code: TRUE

But none of the zones is created in Amazon. There is not a specific error that stands out related to this domain.

The domain existed a while in Amazon but was removed recently. We wanted to re-add it. Is it possible Amazon still reserves is somewhere, although not visible? Also, I can create it manually.. (but it will not update with Plesk <> Amazon)

Does Modules_Route53_Logger log to panel.log? Cause I don't see any of the log entries from route53.php in panel.log.

**Comment by nielsvr** [comment]
Alright, not sure what or how; but suddenly it's working.

Is there a pending status or something after removal? If so, maybe a check or log about it would make it easier to debug.

**Comment by ayamshanov** [comment]
When you enable debug in panel.ini, uncomment "_filter.priority = 7_" and "_show.util_exec = on_".

If you still don't see logs from Route53 like...

> `[...] DEBUG [panel] DNS Custom backend call: [...]`
> `[...] DEBUG [extension/route53] [5b0fcce392c44] Starting: /opt/psa/admin/plib/modules/route53/scripts/route53.php`
> `[...] DEBUG [extension/route53] [5b0fcce392c44] Finished in 1.7431s, Error code: 0`
> `[...] INFO [panel] Execution /opt/psa/admin/plib/modules/route53/scripts/route53.php done.`

..., check what backend script configured with command "`plesk db show ServiceNodeConfiguration | grep dnsConnector`".

The output should be like this:
> `| 1 | dnsConnector | custom         | true`
> `| 1 | dnsConnector | custom_script  | "/opt/psa/bin/extension" --exec route53 route53.php`
> `| 1 | dnsConnector | plesk            | true`

I hope this information helps you.

If the issue repeated, could you please provide an output of these commands and information what version of Plesk, Route53, OS you use.
