### ISSUE TITLE
(Feature) (White Label DNS) Ability to change default SOA and NS records

### ISSUE THREAD

**Issue by iget-master** [plesk/ext-route53#30]
We are using this extension to manage a server with Route53 DNS, and we configured the route 53 as a white label dns, so instead of using `ns-XXX.awsdns-XX.net`, I want to use `ns1.mydomain.com`.

The problem is that even I changing the default nameservers on plesk settings, it's using the reusable delegation set's nameservers when I create new domains, and simply don't respect the NS entries that I put on the domain DNS Zone settings. 

Apparently the problem is on this two commented lines:

https://github.com/plesk/ext-route53/blob/3c8a5050a261574b5d1b6faacfc4cbf27dbc30c4/src/plib/scripts/route53.php#L24-L37

That are preventing the SOA records being used.

# My suggestion

IMO, the extension should have a setting that allow renaming the Reusable Delegation Set nameservers, and use that Nameservers to configure the domains.

**Comment by toshidex** [comment]
Please integrate this feature. I needed!
