### ISSUE TITLE
Adding PTR record Issue

### ISSUE THREAD

**Issue by stevewest15** [plesk/ext-route53#8]
Amazon Route 53 version: 1.3.1

If I try to add a PTR record via Plesk, the record doesn't get added to Amazon Route 53. I can add other records fine but it doesn't look like PTR records are working.

Here is a screencast of the steps I did:

http://screencast.com/t/Z0g4zhlm

Let me know if there are any questions.

Thx,

SW

**Comment by vlikhtanskiy** [comment]
Hello,

In fact PTR records shouldn't be in your DNS zone. They should be in reverse DNS zone. You can see the same in official documentation: https://aws.amazon.com/premiumsupport/knowledge-center/route-53-reverse-dns/ 

It is specifics of Plesk that these records are shown inside DNS zone.
